# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # config.vm.box = "fullbright/station-manual"
  config.vm.box = "ubuntu/focal64"

  config.vm.provider :virtualbox do |v|
    v.gui = true
    v.name = "brightstation"
    v.memory = 2048
    v.cpus = 1
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
  end

  config.vm.hostname = "brightstation"
  config.vm.network :private_network, ip: "192.168.10.102"

  config.ssh.insert_key = false

  # Set the name of the VM. See: http://stackoverflow.com/a/17864388/100134
  config.vm.define :brightstation do |brightstation|
  end

  # Create the pi user so that we can sync data into his home folder
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    sudo useradd -m pi
    apt-get install gnome-session -y
  SHELL
end
