---
# playbook.yml
- name: 'Provision Image'
  hosts: default
  become: true

  roles:
    - geerlingguy.packer

  tasks:
    - name: install vim
      package:
        name: 'vim'
        state: present
